services:
  - type: web
    name: kuriftu-fastapi
    runtime: python
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kuriftu-db
          property: connectionString
